[package]
name = "cfri-blaze"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aes = "0.8"
ark-std = { version = "0.4", default-features = false }
bincode = "1.3"
bitvec = "1"
blake2 = "0.10"
blake2b_simd = "1"
crossbeam = "0.8"
ctr = { git = "https://github.com/RustCrypto/block-modes", rev = "78fefba5a80f3d788fd8ba7c4483625148f5dc18" }
ff = { version = "0.13", features = ["derive"] }
generic-array = { version = "0.14", features = ["serde"] }
halo2_curves = { git = "https://github.com/privacy-scaling-explorations/halo2curves", tag = "v0.4.0", package = "halo2curves", features = ["derive_serde"] }
halo2_proofs = { git = "https://github.com/han0110/halo2.git", branch = "feature/for-benchmark", optional = true }
hex-literal = "0.4"
itertools = "0.13"
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
pasta_curves = { version = "0.5", features = ["serde"] }
poseidon = { git = "https://github.com/han0110/poseidon", branch = "feature/with-spec" }
rand = "0.8"
rand_chacha = { version = "0.3", features = ["serde1"] }
rayon = "1"
serde = { version = "1", features = ["derive"] }
sha3 = "0.10"
subtle = "2"
threadpool = "1"

[features]
default = ["parallel", "frontend-halo2", "sanity-check"]
benchmark = ["parallel"]
frontend-halo2 = ["dep:halo2_proofs"]
parallel = []
sanity-check = []
upstream-tests = []

[dev-dependencies]
criterion = "0.4"
paste = "1"
