[package]
name = "cfri"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
deepfold = { path = "../../third_party/pipfri/deepfold" }
de_pip_fri = { path = "../../third_party/pipfri/de_pip_fri" }
fri = { path = "../../third_party/pipfri/fri" }
pip_fri = { path = "../../third_party/pipfri/pip_fri" }
polyfrim = { path = "../../third_party/pipfri/polyfrim" }
virgo = { path = "../../third_party/pipfri/virgo" }

[dev-dependencies]
ark-ff = "0.4"
ark-poly = "0.4"
pipfri_utils = { package = "utils", path = "../../third_party/pipfri/utils" }
rand = "0.8"
